name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/fixcvnow-backend/htdocs/backend.fixcvnow.com
            git pull origin main
            npm install
            pm2 reload backend || pm2 start ecosystem.config.cjs
            pm2 save
