import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { COLORS } from '@/lib/colors'

const sections = [
  {
    title: '1. Use of Artificial Intelligence',
    content: `FixCVNow uses artificial intelligence and automated processing tools to analyse and improve resumes. These systems may:
• Correct grammar and spelling
• Improve formatting and structure
• Generate profile summaries
• Suggest improved phrasing
• Extract and organize skills
• Optimize resume wording

AI is used to assist in generating suggestions intended to improve the presentation of a resume.`,
  },
  {
    title: '2. AI Output May Contain Errors',
    content: `Artificial intelligence systems are not perfect and may occasionally produce:
• Inaccurate suggestions
• Incomplete information
• Incorrect wording
• Formatting inconsistencies
• Contextually inappropriate content

Users must carefully review all AI-generated content before using the resume for job applications.`,
  },
  {
    title: '3. User Responsibility',
    content: `The final responsibility for the accuracy and appropriateness of the resume remains with the user. Users should verify:
• Job titles
• Employment history
• Skills and qualifications
• Dates of employment
• Achievements and responsibilities

FixCVNow does not verify or validate the factual accuracy of resume information.`,
  },
  {
    title: '4. No Guarantee of Employment Outcomes',
    content: `FixCVNow is a resume improvement tool. Use of FixCVNow does not guarantee:
• Job interviews
• Job offers
• Employer responses
• Career advancement

Hiring decisions are made solely by employers and are influenced by many factors beyond the scope of this service.`,
  },
  {
    title: '5. AI Suggestions Are Optional',
    content: `Users are not required to use all suggestions generated by the AI. Users may edit, modify, or remove any AI-generated content before using their resume.`,
  },
  {
    title: '6. Limitation of Liability',
    content: `To the maximum extent permitted by law, FixCVNow shall not be responsible for:
• Errors in AI-generated resume content
• Employment decisions made by recruiters or employers
• Loss of job opportunities
• Any direct or indirect consequences arising from the use of AI-generated content

Users assume full responsibility for reviewing and using their resumes.`,
  },
  {
    title: '7. Continuous Improvement of AI Systems',
    content: `FixCVNow continuously works to improve its AI systems and may update or modify the AI models used to provide resume improvements. The functionality and outputs of AI systems may change over time as improvements are made.`,
  },
  {
    title: '8. Acceptance of AI Processing',
    content: `By uploading your resume and using FixCVNow, you acknowledge that your resume will be processed by automated AI systems in order to generate improvements.`,
  },
  {
    title: '9. Contact Information',
    content: `If you have questions about how AI is used in FixCVNow, please contact:\nEmail: support@fixcvnow.com\nWebsite: https://www.fixcvnow.com`,
  },
]

export default function AIDataUsagePage() {
  return (
    <div className="min-h-screen flex flex-col bg-white">
      <Navbar />
      <main className="flex-1">
        <div className="py-16 px-6 text-center" style={{ backgroundColor: COLORS.bgLight }}>
          <div className="max-w-3xl mx-auto">
            <h1 className="text-4xl md:text-5xl font-extrabold mb-3" style={{ color: COLORS.blue }}>
              AI &amp; Data Usage Policy
            </h1>
            <p className="text-slate-400 text-sm">Last Updated: 1st April 2026</p>
          </div>
        </div>

        <div className="max-w-3xl mx-auto px-6 py-16">
          <p className="text-slate-600 mb-12 leading-relaxed">
            This AI Usage Disclaimer explains the role of artificial intelligence in the FixCVNow service and the limitations associated with AI-generated outputs. By using FixCVNow, you acknowledge and agree to the terms described in this disclaimer.
          </p>

          <div className="space-y-10">
            {sections.map((s) => (
              <div key={s.title}>
                <h2 className="text-lg font-bold mb-3" style={{ color: COLORS.blue }}>{s.title}</h2>
                <p className="text-slate-600 text-sm leading-relaxed whitespace-pre-line">{s.content}</p>
              </div>
            ))}
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
